package renderer

import (
	"bytes"
	"fmt"
	"image/png"

	"github.com/fogleman/gg"
	"github.com/golang/freetype/truetype"
	"golang.org/x/image/font/gofont/gobold"
	"golang.org/x/image/font/gofont/goregular"

	"github.com/arkcode369/ff-calendar-bot/internal/domain"
	"github.com/arkcode369/ff-calendar-bot/pkg/fmtutil"
)

// GenerateCOTRawImage returns a PNG byte slice representing a beautiful dashboard card.
func GenerateCOTRawImage(analysis domain.COTAnalysis) ([]byte, error) {
	const width = 800
	const height = 600
	dc := gg.NewContext(width, height)

	// Background (Dark mode)
	dc.SetHexColor("#1E1E2E")
	dc.Clear()

	// Load Fonts from embedded Go fonts
	fontRegular, err := truetype.Parse(goregular.TTF)
	if err != nil {
		return nil, err
	}
	fontBold, err := truetype.Parse(gobold.TTF)
	if err != nil {
		return nil, err
	}

	faceRegular := truetype.NewFace(fontRegular, &truetype.Options{Size: 18})
	faceBold := truetype.NewFace(fontBold, &truetype.Options{Size: 24})
	faceTitle := truetype.NewFace(fontBold, &truetype.Options{Size: 36})
	faceSmall := truetype.NewFace(fontRegular, &truetype.Options{Size: 14})

	// Header
	dc.SetFontFace(faceTitle)
	dc.SetHexColor("#CBA6F7") // Soft purple
	dc.DrawString(fmt.Sprintf("%s (%s) COT Data", analysis.Contract.Name, analysis.Contract.Currency), 40, 60)

	dc.SetFontFace(faceSmall)
	dc.SetHexColor("#A6ADC8")
	dc.DrawString(fmt.Sprintf("Report Date: %s | Generated by FF Calendar Bot", analysis.ReportDate.Format("02 Jan 2006")), 40, 85)

	dc.DrawLine(40, 100, 760, 100)
	dc.SetHexColor("#45475A")
	dc.SetLineWidth(2)
	dc.Stroke()

	// Helper to draw a card
	drawCard := func(x, y, w, h float64, title string, value string, valColor string, subtext string) {
		dc.SetHexColor("#313244")
		dc.DrawRoundedRectangle(x, y, w, h, 10)
		dc.Fill()

		dc.SetFontFace(faceSmall)
		dc.SetHexColor("#BAC2DE")
		dc.DrawString(title, x+20, y+30)

		dc.SetFontFace(faceBold)
		dc.SetHexColor(valColor)
		dc.DrawString(value, x+20, y+70)

		if subtext != "" {
			dc.SetFontFace(faceSmall)
			dc.SetHexColor("#A6ADC8")
			dc.DrawString(subtext, x+20, y+100)
		}
	}

	// Define colors
	bullColor := "#A6E3A1" // Green
	bearColor := "#F38BA8" // Red
	neutralColor := "#F9E2AF" // Yellow
	
	netColor := neutralColor
	if analysis.NetPosition > 0 {
		netColor = bullColor
	} else if analysis.NetPosition < 0 {
		netColor = bearColor
	}

	// 1. Smart Money Net Position
	drawCard(40, 130, 340, 120, "Smart Money Net Position", fmtutil.FmtNumSigned(analysis.NetPosition, 0), netColor, fmt.Sprintf("Change: %s", fmtutil.FmtNumSigned(analysis.NetChange, 0)))

	// 2. COT Index
	cotColor := neutralColor
	if analysis.COTIndex > 80 {
		cotColor = bullColor
	} else if analysis.COTIndex < 20 {
		cotColor = bearColor
	}
	drawCard(420, 130, 340, 120, "COT Index (52W)", fmt.Sprintf("%.0f%%", analysis.COTIndex), cotColor, "0%% = Extreme Short, 100%% = Extreme Long")

	// 3. 4W Momentum
	momColor := neutralColor
	if analysis.SpecMomentum4W > 0 {
		momColor = bullColor
	} else if analysis.SpecMomentum4W < 0 {
		momColor = bearColor
	}
	drawCard(40, 270, 340, 120, "4-Week Momentum", fmtutil.FmtNumSigned(analysis.SpecMomentum4W, 0), momColor, string(analysis.MomentumDir))

	// 4. Open Interest Trend
	oiColor := neutralColor
	if analysis.OITrend == "RISING" {
		oiColor = bullColor
	} else if analysis.OITrend == "FALLING" {
		oiColor = bearColor
	}
	drawCard(420, 270, 340, 120, "Open Interest Trend", analysis.OITrend, oiColor, fmt.Sprintf("Change: %s (%.1f%%)", fmtutil.FmtNumSigned(analysis.OpenInterestChg, 0), analysis.OIPctChange))

	// 5. Short-Term Bias (Scalper Intel)
	biasColor := neutralColor
	if analysis.ShortTermBias == "STRONG BUY (BUY DIPS)" || analysis.ShortTermBias == "WEAK BUY (SELL RALLIES)" {
		biasColor = bullColor
	} else if analysis.ShortTermBias == "STRONG SELL (SELL RALLIES)" || analysis.ShortTermBias == "WEAK SELL (BUY DIPS)" {
		biasColor = bearColor
	}
	
	dc.SetHexColor("#313244")
	dc.DrawRoundedRectangle(40, 410, 720, 100, 10)
	dc.Fill()

	dc.SetFontFace(faceRegular)
	dc.SetHexColor("#BAC2DE")
	dc.DrawStringAnchored("Intraday / Scalper Bias", width/2, 440, 0.5, 0.5)

	dc.SetFontFace(faceTitle)
	dc.SetHexColor(biasColor)
	dc.DrawStringAnchored(analysis.ShortTermBias, width/2, 480, 0.5, 0.5)

	// Render to PNG
	var buf bytes.Buffer
	if err := png.Encode(&buf, dc.Image()); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
